### ISSUE TITLE
download 1 Video/ Clip at a time

### ISSUE THREAD

**Issue by ausafali** [thefiz/TwitchClipDownloader#4]
please make tool like this, it download 1 clip or video download at a time. after 1st download complete grab next link and start downloading and so on

**Comment by thefiz** [comment]
I had a bug in the code where it wasn't advising you when the downloads were complete, instead putting the text up immediately.  I have solved that issue.  I am exploring limiting the amount of simultaneous downloads for performance sake.  What you suggest is possible, but would slow down the process greatly for those on fast connections.  So I have to find a happy medium.
