### ISSUE TITLE
Duplicating videos

### ISSUE THREAD

**Issue by Nezzy2** [thefiz/TwitchClipDownloader#6]
Some clips are downloaded then others are simply a duplicated version of the last linked clip with a renamed title

**Comment by Nezzy2** [comment]
Some clips are downloaded then others are simply a duplicated version of the last linked clip with a renamed title of a previous linked clip

**Comment by thefiz** [comment]
I will take a look at this today, I haven’t seen this myself.

**Comment by thefiz** [comment]
I have replicated this issue, tracking it down now

**Comment by thefiz** [comment]
Fixed in v1.4 on the releases page
